export const fileNames = {
  node: [
    "package.json",
    "README.md",
    ".gitignore",
    "constant",
    ".env",
    "utils",
    "service",
    "routers",
    "router",
  ],
  react: [
    "package.json",
    "README.md",
    ".gitignore",
    "src/constant",
    "src/components",
    "src/actions",
    "src/reducers",
  ],
  ror: [
    "README.md",
    ".gitignore",
    "db",
    "seeds.rb",
    "schema.rb",
    "Rakefile",
    "constant",
    "Gemfile",
    "config",
    "config.ru",
    "controllers",
    "models",
  ],
};
