export const fileNames = {
  node: [
    "constant",
    "config.js",
    ".env",
    "utils",
    "service",
    "routers",
    "router",
    "server.js",
  ],
  react: ["src/constant", "src/components", "src/actions", "src/reducers"],
  ror: [
    "db",
    "seeds.rb",
    "schema.rb",
    "Rakefile",
    "constant",
    "Gemfile",
    "config",
    "environments/development.rb",
    "environments/production.rb",
    "environments/test.rb",
    "config.ru",
    "app",
    "app/controllers",
    "app/models",
    "app/view",
    "app/helpers",
  ],
  common: ["README.md", ".gitignore", "package.json"],
};
