export const constantFileList = {
  node: [
    "constant",
    "config.js",
    ".env",
    "utils",
    "service",
    "routers",
    "router",
    "server.js",
    "migrations",
  ],
  react: ["src", "constant", "components", "actions", "reducers"],
  ror: [
    "db",
    "seeds.rb",
    "schema.rb",
    "Rakefile",
    "constant",
    "Gemfile",
    "config",
    "environments",
    "development.rb",
    "production.rb",
    "test.rb",
    "config.ru",
    "app",
    "controllers",
    "models",
    "view",
    "helpers",
  ],
  common: ["README.md", ".gitignore", "package.json", "index.js"],
};
